title: It Will Never Work in Theory
subtitle: Short summaries of recent results in empirical software engineering research
url: https://neverworkintheory.org
repository: neverworkintheory/neverworkintheory.github.com
repositoryurl: https://github.com/neverworkintheory/neverworkintheory.github.io/

markdown: kramdown
highlighter: rouge
permalink: "/:year/:month/:day/:title.html"
paginate: 10
paginate_path: /blog/:num

blog:
  truncated_preview: true

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Greg Wilson
  url: https://third-bit.com
  email: gvwilson@third-bit.com

years:
  - 2011
  - 2012
  - 2013
  - 2014
  - 2015
  - 2016
  - 2017
  - 2021
  - 2022

talks:
  - title: "Online"
    date: "April 2022"
    talks:
      - thumbnail: "2022-04-aniche.webp"
        title: "How code coverage can be used and abused to guide testing"
        homepage: "https://www.mauricioaniche.com/"
        speaker: "Maurício Aniche"
        video: "https://youtu.be/f1DueZcSxRs"
      - thumbnail: "2022-04-bacchelli.webp"
        title: "How code review works (and doesn't) in the real world"
        homepage: "https://sback.it/"
        speaker: "Alberto Bacchelli"
        video: "https://youtu.be/_SJL7vepQvU"
      - thumbnail: "2022-04-baltes.webp"
        title: "Challenges and opportunities for software engineering in Papua New Guinea"
        homepage: "https://empirical-software.engineering/"
        speaker: "Sebastian Baltes"
        video: "https://youtu.be/SsHf0-X4vrI"
      - thumbnail: "2022-04-blincoe.webp"
        title: "The effects of destructive criticism in code review"
        homepage: "https://kblincoe.github.io/"
        speaker: "Kelly Blincoe"
        video: "https://youtu.be/qaO00CLqLkI"
      - thumbnail: "2022-04-brown.webp"
        title: "How your minds learn to program"
        homepage: "https://twistedsquare.com/"
        speaker: "Neil Brown"
        video: "https://youtu.be/FAXAPBxkhxc"
      - thumbnail: "2022-04-ford-robinson.webp"
        title: "Online community and safety in software engineering"
        homepage: "http://denaeford.me/"
        speaker: "Denae Ford Robinson"
        video: "https://youtu.be/kkPLEMevjlw"
      - thumbnail: "2022-04-fucci.webp"
        title: "The hidden costs and benefits of TDD"
        homepage: "https://dfucci.github.io/"
        speaker: "Davide Fucci"
        video: "https://youtu.be/rBcV1F7jyHw"
      - thumbnail: "2022-04-galster.webp"
        title: "Value and waste in software engineering"
        homepage: "https://www.csse.canterbury.ac.nz/matthias.galster/"
        speaker: "Matthias Galster"
        video: "https://youtu.be/MVTO4KCRKJw"
      - thumbnail: "2022-04-hermans.webp"
        title: "How patterns in variable names can make code easier to read"
        homepage: "https://www.felienne.com/"
        speaker: "Felienne Hermans"
        video: "https://youtu.be/z7w2lKG8zWM"
      - thumbnail: "2022-04-hicks.webp"
        title: "Fostering a learning culture in coding teams"
        homepage: "https://www.catharsisinsight.com/"
        speaker: "Catherine Hicks"
        video: "https://youtu.be/ygeykeP9Ww4"
      - thumbnail: "2022-04-johnson-matthews.webp"
        title: "Causal testing: understanding the root causes of defects"
        homepage: "https://cs.gmu.edu/~johnsonb/"
        speaker: "Brittany Johnson-Matthews"
        video: "https://youtu.be/SrDqrwyV4I4"
      - thumbnail: "2022-04-mcintosh.webp"
        title: "The unintended consequences of mining software build systems"
        homepage: "https://shanemcintosh.org/"
        speaker: "Shane McIntosh"
        video: "https://youtu.be/QJvijeRx8ic"
      - thumbnail: "2022-04-nagappan.webp"
        title: "Bias in evaluating code contributions"
        homepage: "https://cs.uwaterloo.ca/~m2nagapp/"
        speaker: "Mei Nagappan"
        video: "https://youtu.be/oPIVZe0c3Io"
      - thumbnail: "2022-04-petre.webp"
        title: "How expert programmers think about errors"
        homepage: "http://mcs.open.ac.uk/mp8/"
        speaker: "Marian Petre"
        video: "https://youtu.be/Jor-Rh0gwus"
      - thumbnail: "2022-04-rigger.webp"
        title: "How to test software without writing tests"
        homepage: "https://www.manuelrigger.at/"
        speaker: "Manuel Rigger"
        video: "https://youtu.be/tLKTILnVasg"
      - thumbnail: "2022-04-rodeghero.webp"
        title: "What we've learned about remote onboarding during the pandemic"
        homepage: "https://paigerodeghero.com/"
        speaker: "Paige Rodeghero"
        video: "https://youtu.be/sVAPJ2JvU78"
      - thumbnail: "2022-04-steinmacher.webp"
        title: "Negotiation and padding in software project estimates"
        homepage: "http://igor.pro.br/"
        speaker: "Igor Steinmacher"
        video: "https://youtu.be/zpPDlVoiVSU"
      - thumbnail: "2022-04-stolee.webp"
        title: "To search or not to search: it depends on the question"
        homepage: "http://kstolee.github.io/"
        speaker: "Kathryn Stolee"
        video: "https://youtu.be/iiJXYO_hcvQ"
      - thumbnail: "2022-04-storey.webp"
        title: "What does 'productivity' actually mean for developers?"
        homepage: "https://www.margaretstorey.com/"
        speaker: "Margaret-Anne Storey"
        video: "https://youtu.be/ZdUAxUBrYLA"
      - thumbnail: "2022-04-treude.webp"
        title: "Automatically enhancing error messages"
        homepage: "https://ctreude.ca/"
        speaker: "Christoph Treude"
        video: "https://youtu.be/YP5BGiw0Gng"
      - thumbnail: "2022-04-wessel.webp"
        title: "How people really use GitHub Actions"
        homepage: "https://mairieli.com/"
        speaker: "Mairieli Wessel"
        video: "https://youtu.be/X1Z9lWhQaro"
      - thumbnail: "2022-04-zaidman.webp"
        title: "Programmer by day, tester by night"
        homepage: "https://azaidman.github.io/"
        speaker: "Andy Zaidman"
        video: "https://youtu.be/rFXdQ0k-hqw"
  - title: "Strange Loop"
    date: "October 2022"
    talks:
      - thumbnail: "2022-10-brown.webp"
        title: "How to recommend tools for finding and fixing software errors"
        homepage: "https://chbrown13.github.io/"
        speaker: "Chris Brown"
        video: "https://youtu.be/P_x3M57paZ8"
      - thumbnail: "2022-10-hicks.webp"
        title: "It's like coding in the dark: the need for learning culture within engineering teams"
        homepage: "https://www.catharsisinsight.com/"
        speaker: "Catherine Hicks"
        video: "https://youtu.be/mVec1TzQIMM"
      - thumbnail: "2022-10-khomh.webp"
        title: "Finding bugs in deep learning programs"
        homepage: "http://khomh.net/"
        speaker: "Foutse Khomh"
        video: "https://youtu.be/1L8t3OldBfc"
      - thumbnail: "2022-10-mkaouer.webp"
        title: "One thousand and one stories: a large-scale survey of software refactoring"
        homepage: "https://mkaouer.net/"
        speaker: "Mohamed Wiem Mkaouer"
        video: "https://youtu.be/rUa_hELXvHs"
      - thumbnail: "2022-10-nadi.webp"
        title: "It's not you, it's the API: automatically avoiding API misuses"
        homepage: "https://www.sarahnadi.org/"
        speaker: "Sarah Nadi"
        video: "https://youtu.be/KqhvZ4xTnhQ"
      - thumbnail: "2022-10-santos.webp"
        title: "Choose wisely: code smells in automatically generated code"
        homepage: "https://joannacss.github.io/"
        speaker: "Joanna Cecilia da Silva Santos"
        video: "https://youtu.be/GIV-ZyjWtg0"
      - thumbnail: "2022-10-smith.webp"
        title: "How automated tools can communicate effective strategies for fixing bugs"
        homepage: "https://jssmith1.github.io/"
        speaker: "Justin Smith"
        video: "https://youtu.be/_I-DM5z8UeY"
      - thumbnail: "2022-10-zhang.webp"
        title: "Interactive debugging and testing support for deep learning"
        homepage: "https://tianyi-zhang.github.io/"
        speaker: "Tianyi Zhang"
        video: "https://youtu.be/8LekgPnRt1g"

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - '*.sublime-*'
  - '*.aux'
  - '*.bbl'
  - '*.blg'
  - '*.log'
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
  - vendor/bundle
  - bin
